# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorter', '0009_auto_20180508_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.ImageField(default=0, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cut_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorter.CutURL')),
            ],
        ),
    ]
