# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0004_cuturl_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuturl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
