# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0006_auto_20180504_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuturl',
            old_name='shortCode',
            new_name='shortcode',
        ),
        migrations.RenameField(
            model_name='cuturl',
            old_name='update',
            new_name='updated',
        ),
    ]
