# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0007_auto_20180504_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuturl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
