# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import shorter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0008_cuturl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuturl',
            name='url',
            field=models.CharField(max_length=220, validators=[shorter.validators.validate_url, shorter.validators.validate_dot_com]),
        ),
    ]
